[package]
name = "dot-dodger"
version = "0.1.0"
authors = ["Victor Bankowski <victor_bankowski@hotmail.com>"]
edition = "2018"

[dependencies]
kolli-desu = { git = "https://github.com/WaDelma/kolli-desu"}
specs-derive = "0.3"
nalgebra = "0.14"
modulator = "0.1.0"

[dependencies.amethyst]
version = "0.10.0"
features = ["nightly"]